-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#111318', -- 背景
  base01 = '#0c0e13', --较浅的背景色
  base02 = '#191c20',
  base03 = '#abc7ff', -- 键盘字符，匹配大括号
  base04 = '#c4c6d0',
  base05 = '#abc7ff', -- 括号，运算符
  base06 = '#2e3036',
  base07 = '#37393e',

  base08 = '#ddbce0',-- 变量名
  base09 = '#dae2f9', -- 整数、布尔值 (True/False)。
  base0A = '#bec6dc', --类名 (Class)、搜索匹配到的背景
  base0B = '#abc7ff', -- 字符串
  base0C = '#ddbce0',
  base0D = '#284677', -- 函数名
  base0E = '#bec6dc', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#e2e2e9', -- 选中文字背景
  fg = '#111318', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8e9099', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#ddbce0',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#bec6dc',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#415e91',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#1e2025', --底边
  fg = '#abc7ff',
})
